apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-k8s.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: filtration-query
  name: filtration-query
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filtration-query
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-k8s.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: filtration-query
    spec:
      containers:
        - image: filtration-query:latest
          imagePullPolicy: IfNotPresent
          name: filtration-query
          ports:
            - containerPort: 50056
          resources: {}
      restartPolicy: Always
status: {}
