apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-k8s.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: filtration-query
  name: filtration-query
spec:
  ports:
    - name: "50056"
      port: 50056
      targetPort: 50056
  selector:
    io.kompose.service: filtration-query
status:
  loadBalancer: {}
