apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: filtration-query
build:
  artifacts:
  - image: filtration-query
    docker:
      dockerfile: Dockerfile.local
deploy:
  kubectl:
    manifests:
    - filtration-query-deployment.yaml
    - filtration-query-service.yaml
