// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pb/filtrationquerypb/filtrationquery.proto

package filtrationquerypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Unit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Unit) Reset() {
	*x = Unit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_pb_filtrationquerypb_filtrationquery_proto_rawDescGZIP(), []int{0}
}

func (x *Unit) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Unit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_pb_filtrationquerypb_filtrationquery_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Filter) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Dirt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Dirt) Reset() {
	*x = Dirt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dirt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dirt) ProtoMessage() {}

func (x *Dirt) ProtoReflect() protoreflect.Message {
	mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dirt.ProtoReflect.Descriptor instead.
func (*Dirt) Descriptor() ([]byte, []int) {
	return file_pb_filtrationquerypb_filtrationquery_proto_rawDescGZIP(), []int{2}
}

func (x *Dirt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dirt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GroupId string `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pb_filtrationquerypb_filtrationquery_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type Filtration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FoFilterCondition int32   `protobuf:"varint,2,opt,name=fo_filter_condition,json=foFilterCondition,proto3" json:"fo_filter_condition,omitempty"`
	CreatedAt         string  `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	AoFollowedUpDate  string  `protobuf:"bytes,4,opt,name=ao_followed_up_date,json=aoFollowedUpDate,proto3" json:"ao_followed_up_date,omitempty"`
	AoConclusion      int32   `protobuf:"varint,5,opt,name=ao_conclusion,json=aoConclusion,proto3" json:"ao_conclusion,omitempty"`
	CompletedDate     string  `protobuf:"bytes,6,opt,name=completed_date,json=completedDate,proto3" json:"completed_date,omitempty"`
	Status            int32   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Unit              *Unit   `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	Filter            *Filter `protobuf:"bytes,9,opt,name=filter,proto3" json:"filter,omitempty"`
	Dirt              *Dirt   `protobuf:"bytes,10,opt,name=dirt,proto3" json:"dirt,omitempty"`
}

func (x *Filtration) Reset() {
	*x = Filtration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filtration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filtration) ProtoMessage() {}

func (x *Filtration) ProtoReflect() protoreflect.Message {
	mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filtration.ProtoReflect.Descriptor instead.
func (*Filtration) Descriptor() ([]byte, []int) {
	return file_pb_filtrationquerypb_filtrationquery_proto_rawDescGZIP(), []int{4}
}

func (x *Filtration) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Filtration) GetFoFilterCondition() int32 {
	if x != nil {
		return x.FoFilterCondition
	}
	return 0
}

func (x *Filtration) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Filtration) GetAoFollowedUpDate() string {
	if x != nil {
		return x.AoFollowedUpDate
	}
	return ""
}

func (x *Filtration) GetAoConclusion() int32 {
	if x != nil {
		return x.AoConclusion
	}
	return 0
}

func (x *Filtration) GetCompletedDate() string {
	if x != nil {
		return x.CompletedDate
	}
	return ""
}

func (x *Filtration) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Filtration) GetUnit() *Unit {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *Filtration) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *Filtration) GetDirt() *Dirt {
	if x != nil {
		return x.Dirt
	}
	return nil
}

type GetFiltrationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nophoto           string `protobuf:"bytes,1,opt,name=nophoto,proto3" json:"nophoto,omitempty"`
	Page              string `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Perpage           string `protobuf:"bytes,3,opt,name=perpage,proto3" json:"perpage,omitempty"`
	Statuses          string `protobuf:"bytes,4,opt,name=statuses,proto3" json:"statuses,omitempty"`
	FilterId          string `protobuf:"bytes,5,opt,name=filter_id,json=filterId,proto3" json:"filter_id,omitempty"`
	Date              string `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	FoFilterCondition string `protobuf:"bytes,8,opt,name=fo_filter_condition,json=foFilterCondition,proto3" json:"fo_filter_condition,omitempty"`
}

func (x *GetFiltrationsRequest) Reset() {
	*x = GetFiltrationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFiltrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFiltrationsRequest) ProtoMessage() {}

func (x *GetFiltrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFiltrationsRequest.ProtoReflect.Descriptor instead.
func (*GetFiltrationsRequest) Descriptor() ([]byte, []int) {
	return file_pb_filtrationquerypb_filtrationquery_proto_rawDescGZIP(), []int{5}
}

func (x *GetFiltrationsRequest) GetNophoto() string {
	if x != nil {
		return x.Nophoto
	}
	return ""
}

func (x *GetFiltrationsRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *GetFiltrationsRequest) GetPerpage() string {
	if x != nil {
		return x.Perpage
	}
	return ""
}

func (x *GetFiltrationsRequest) GetStatuses() string {
	if x != nil {
		return x.Statuses
	}
	return ""
}

func (x *GetFiltrationsRequest) GetFilterId() string {
	if x != nil {
		return x.FilterId
	}
	return ""
}

func (x *GetFiltrationsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetFiltrationsRequest) GetFoFilterCondition() string {
	if x != nil {
		return x.FoFilterCondition
	}
	return ""
}

type GetFiltrationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filtrations []*Filtration `protobuf:"bytes,1,rep,name=filtrations,proto3" json:"filtrations,omitempty"`
	Total       int64         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page        int64         `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	LastPage    int64         `protobuf:"varint,4,opt,name=last_page,json=lastPage,proto3" json:"last_page,omitempty"`
}

func (x *GetFiltrationsResponse) Reset() {
	*x = GetFiltrationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFiltrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFiltrationsResponse) ProtoMessage() {}

func (x *GetFiltrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFiltrationsResponse.ProtoReflect.Descriptor instead.
func (*GetFiltrationsResponse) Descriptor() ([]byte, []int) {
	return file_pb_filtrationquerypb_filtrationquery_proto_rawDescGZIP(), []int{6}
}

func (x *GetFiltrationsResponse) GetFiltrations() []*Filtration {
	if x != nil {
		return x.Filtrations
	}
	return nil
}

func (x *GetFiltrationsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFiltrationsResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFiltrationsResponse) GetLastPage() int64 {
	if x != nil {
		return x.LastPage
	}
	return 0
}

var File_pb_filtrationquerypb_filtrationquery_proto protoreflect.FileDescriptor

var file_pb_filtrationquerypb_filtrationquery_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x62, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x69,
	0x6c, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x70, 0x62, 0x22,
	0x2a, 0x0a, 0x04, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x06, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2a, 0x0a, 0x04, 0x44, 0x69, 0x72,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x45, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x8a, 0x03, 0x0a,
	0x0a, 0x46, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x66,
	0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x66, 0x6f, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2d, 0x0a, 0x13, 0x61, 0x6f, 0x5f,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x75, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x6f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x55, 0x70, 0x44, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6f, 0x5f, 0x63,
	0x6f, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x61, 0x6f, 0x43, 0x6f, 0x6e, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x04,
	0x75, 0x6e, 0x69, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x66, 0x69, 0x6c,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x55,
	0x6e, 0x69, 0x74, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x69, 0x6c, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x04,
	0x64, 0x69, 0x72, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x66, 0x69, 0x6c,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x44,
	0x69, 0x72, 0x74, 0x52, 0x04, 0x64, 0x69, 0x72, 0x74, 0x22, 0xdc, 0x01, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x65, 0x72, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x66, 0x6f, 0x5f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x66, 0x6f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa0, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x61, 0x67, 0x65, 0x32, 0x81, 0x01, 0x0a, 0x16,
	0x46, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x18, 0x5a, 0x16, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pb_filtrationquerypb_filtrationquery_proto_rawDescOnce sync.Once
	file_pb_filtrationquerypb_filtrationquery_proto_rawDescData = file_pb_filtrationquerypb_filtrationquery_proto_rawDesc
)

func file_pb_filtrationquerypb_filtrationquery_proto_rawDescGZIP() []byte {
	file_pb_filtrationquerypb_filtrationquery_proto_rawDescOnce.Do(func() {
		file_pb_filtrationquerypb_filtrationquery_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_filtrationquerypb_filtrationquery_proto_rawDescData)
	})
	return file_pb_filtrationquerypb_filtrationquery_proto_rawDescData
}

var file_pb_filtrationquerypb_filtrationquery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_filtrationquerypb_filtrationquery_proto_goTypes = []interface{}{
	(*Unit)(nil),                   // 0: filtrationquerypb.Unit
	(*Filter)(nil),                 // 1: filtrationquerypb.Filter
	(*Dirt)(nil),                   // 2: filtrationquerypb.Dirt
	(*User)(nil),                   // 3: filtrationquerypb.User
	(*Filtration)(nil),             // 4: filtrationquerypb.Filtration
	(*GetFiltrationsRequest)(nil),  // 5: filtrationquerypb.GetFiltrationsRequest
	(*GetFiltrationsResponse)(nil), // 6: filtrationquerypb.GetFiltrationsResponse
}
var file_pb_filtrationquerypb_filtrationquery_proto_depIdxs = []int32{
	0, // 0: filtrationquerypb.Filtration.unit:type_name -> filtrationquerypb.Unit
	1, // 1: filtrationquerypb.Filtration.filter:type_name -> filtrationquerypb.Filter
	2, // 2: filtrationquerypb.Filtration.dirt:type_name -> filtrationquerypb.Dirt
	4, // 3: filtrationquerypb.GetFiltrationsResponse.filtrations:type_name -> filtrationquerypb.Filtration
	5, // 4: filtrationquerypb.FiltrationQueryService.GetFiltrations:input_type -> filtrationquerypb.GetFiltrationsRequest
	6, // 5: filtrationquerypb.FiltrationQueryService.GetFiltrations:output_type -> filtrationquerypb.GetFiltrationsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_filtrationquerypb_filtrationquery_proto_init() }
func file_pb_filtrationquerypb_filtrationquery_proto_init() {
	if File_pb_filtrationquerypb_filtrationquery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dirt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filtration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFiltrationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_filtrationquerypb_filtrationquery_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFiltrationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_filtrationquerypb_filtrationquery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_filtrationquerypb_filtrationquery_proto_goTypes,
		DependencyIndexes: file_pb_filtrationquerypb_filtrationquery_proto_depIdxs,
		MessageInfos:      file_pb_filtrationquerypb_filtrationquery_proto_msgTypes,
	}.Build()
	File_pb_filtrationquerypb_filtrationquery_proto = out.File
	file_pb_filtrationquerypb_filtrationquery_proto_rawDesc = nil
	file_pb_filtrationquerypb_filtrationquery_proto_goTypes = nil
	file_pb_filtrationquerypb_filtrationquery_proto_depIdxs = nil
}
