version: '3.7'
services:
  master:
    # container_name: master-service
    ports:
      - '50051:50051'
    image: master:latest
    networks:
      - my-network
  user:
    # container_name: user-service
    ports:
      - '50052-50062:50052'
    image: user:latest
    networks:
      - my-network
  bff:
    # container_name: bff-service
    ports:
      - '8080:8080'
    image: bff:latest
    networks:
      - my-network
  mongo:
    # container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - '/Users/tolhah/Documents/Projects/000DATABASE/mongo:/data/db'
    image: mongo
    networks:
      - my-network
  mariadb:
    # container_name: mariadb
    volumes:
      - '/Users/tolhah/Documents/Projects/000DATABASE/mariadb:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    image: 'mariadb:10.5.8'
    networks:
      - my-network

networks:
  my-network:
    # driver: bridge
