version: '3.7'
services:
  mongo:
    # container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - '/Users/tolhah/Documents/Projects/000DATABASE/mongo:/data/db'
    image: mongo
    networks:
      - my-network
  mariadb:
    # container_name: mariadb
    volumes:
      - '/Users/tolhah/Documents/Projects/000DATABASE/mariadb:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    image: 'mariadb:10.5.8'
    networks:
      - my-network
  redis:
    # container_name: redis
    ports:
      - '6379:6379'
    image: redis
    networks:
      - my-network
  prometheus:
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - '/Users/tolhah/Documents/Research/Golang/grpc-ems-2/prometheus.yml:/etc/prometheus/prometheus.yml'
    image: prom/prometheus

networks:
  my-network:
    # driver: bridge
