version: '3.7'
services:
  mongo:
    # container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - '/Users/tolhah/Documents/Projects/000DATABASE/mongo:/data/db'
    image: mongo
    networks:
      - my-network
  mariadb:
    # container_name: mariadb
    volumes:
      - '/Users/tolhah/Documents/Projects/000DATABASE/mariadb:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    image: 'mariadb:10.5.8'
    networks:
      - my-network

networks:
  my-network:
    # driver: bridge
