apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: bff
build:
  artifacts:
  - image: bff
    docker:
      dockerfile: Dockerfile.local
deploy:
  kubectl:
    manifests:
    - bff-deployment.yaml
    - bff-service.yaml
