apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-k8s.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: bff
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bff
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-k8s.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: bff
    spec:
      containers:
        - image: bff:latest
          imagePullPolicy: Never
          name: bff
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
