apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: master
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: master
    spec:
      containers:
        - image: master:latest
          name: master
          ports:
            - containerPort: 50051
          resources: {}
          imagePullPolicy: Never
      restartPolicy: Always
status: {}
