apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-master
  name: mysql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: mysql-master
    spec:
      containers:
        - env:
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: master--env-master
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PORT
                  name: master--env-master
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: master--env-master
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: master--env-master
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: master--env-master
          image: mariadb:10.5.8
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 10
            timeoutSeconds: 20
          name: mysql-master
          ports:
            - containerPort: 3306
          resources: {}
          securityContext:
            capabilities:
              add:
                - all
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-master-claim0
            - mountPath: /etc/my.cnf
              name: mysql-master-claim1
      restartPolicy: Always
      volumes:
        - name: mysql-master-claim0
          persistentVolumeClaim:
            claimName: mysql-master-claim0
        - name: mysql-master-claim1
          persistentVolumeClaim:
            claimName: mysql-master-claim1
status: {}
