// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: commentpb/comment.proto

package commentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QFS
type CreatePackingCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipmentCheckingId int32  `protobuf:"varint,1,opt,name=equipment_checking_id,json=equipmentCheckingId,proto3" json:"equipment_checking_id,omitempty"`
	MrComment           string `protobuf:"bytes,2,opt,name=mr_comment,json=mrComment,proto3" json:"mr_comment,omitempty"`
	MrId                int32  `protobuf:"varint,3,opt,name=mr_id,json=mrId,proto3" json:"mr_id,omitempty"`
}

func (x *CreatePackingCommentRequest) Reset() {
	*x = CreatePackingCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commentpb_comment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePackingCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackingCommentRequest) ProtoMessage() {}

func (x *CreatePackingCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commentpb_comment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackingCommentRequest.ProtoReflect.Descriptor instead.
func (*CreatePackingCommentRequest) Descriptor() ([]byte, []int) {
	return file_commentpb_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePackingCommentRequest) GetEquipmentCheckingId() int32 {
	if x != nil {
		return x.EquipmentCheckingId
	}
	return 0
}

func (x *CreatePackingCommentRequest) GetMrComment() string {
	if x != nil {
		return x.MrComment
	}
	return ""
}

func (x *CreatePackingCommentRequest) GetMrId() int32 {
	if x != nil {
		return x.MrId
	}
	return 0
}

type CreatePackingCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePackingCommentResponse) Reset() {
	*x = CreatePackingCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commentpb_comment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePackingCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackingCommentResponse) ProtoMessage() {}

func (x *CreatePackingCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commentpb_comment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackingCommentResponse.ProtoReflect.Descriptor instead.
func (*CreatePackingCommentResponse) Descriptor() ([]byte, []int) {
	return file_commentpb_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePackingCommentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_commentpb_comment_proto protoreflect.FileDescriptor

var file_commentpb_comment_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x70, 0x62, 0x22, 0x85, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x15, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x13, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x72, 0x5f, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x72,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x72, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x1c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0x7b, 0x0a, 0x0e,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x69,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_commentpb_comment_proto_rawDescOnce sync.Once
	file_commentpb_comment_proto_rawDescData = file_commentpb_comment_proto_rawDesc
)

func file_commentpb_comment_proto_rawDescGZIP() []byte {
	file_commentpb_comment_proto_rawDescOnce.Do(func() {
		file_commentpb_comment_proto_rawDescData = protoimpl.X.CompressGZIP(file_commentpb_comment_proto_rawDescData)
	})
	return file_commentpb_comment_proto_rawDescData
}

var file_commentpb_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_commentpb_comment_proto_goTypes = []interface{}{
	(*CreatePackingCommentRequest)(nil),  // 0: commentpb.CreatePackingCommentRequest
	(*CreatePackingCommentResponse)(nil), // 1: commentpb.CreatePackingCommentResponse
}
var file_commentpb_comment_proto_depIdxs = []int32{
	0, // 0: commentpb.CommentService.CreatePackingComment:input_type -> commentpb.CreatePackingCommentRequest
	1, // 1: commentpb.CommentService.CreatePackingComment:output_type -> commentpb.CreatePackingCommentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commentpb_comment_proto_init() }
func file_commentpb_comment_proto_init() {
	if File_commentpb_comment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_commentpb_comment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePackingCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commentpb_comment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePackingCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commentpb_comment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commentpb_comment_proto_goTypes,
		DependencyIndexes: file_commentpb_comment_proto_depIdxs,
		MessageInfos:      file_commentpb_comment_proto_msgTypes,
	}.Build()
	File_commentpb_comment_proto = out.File
	file_commentpb_comment_proto_rawDesc = nil
	file_commentpb_comment_proto_goTypes = nil
	file_commentpb_comment_proto_depIdxs = nil
}
