apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: packing-cmd
build:
  artifacts:
  - image: packing-cmd
    docker:
      dockerfile: Dockerfile.local
deploy:
  kubectl:
    manifests:
    - packing-cmd-deployment.yaml
    - packing-cmd-service.yaml
